name: Build and test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Hardware In the Loop
    defaults:
      run:
        working-directory: "/tmp/ifred-${GITHUB_JOB}"
    steps:
      - name: "Setup environment variables"
        run: |
          echo "HIL_DIR=/tmp/ifred-${GITHUB_JOB}" >> $GITHUB_ENV
          echo "echo ${HIL_DIR}"
