name: Build and test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Hardware In the Loop
    environment:
      name: ${{ inputs.env }}
    concurrency:
      group: ${{ inputs.env }}
    defaults:
      run:
        working-directory: "/home/github/actions-runner/_work/mqflexv3/mqflexv3/hil-testing/${GITHUB_JOB}"
    steps:
      - name: "Setup environment variables"
        run: |
          echo "HIL_DIR=/home/github/actions-runner/_work/mqflexv3/mqflexv3/hil-testing/${GITHUB_JOB}" >> $GITHUB_ENV
          echo "echo ${HIL_DIR}"
